# Generated by Django 5.2.8 on 2025-11-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], on_delete=django.db.models.deletion.PROTECT, to='webapp.taskstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(choices=[('task', 'Задача'), ('bug', 'Ошибка'), ('enhancement', 'Улучшение')], on_delete=django.db.models.deletion.PROTECT, to='webapp.tasktype', verbose_name='Тип задачи'),
        ),
    ]
