# Generated by Django 5.2.8 on 2025-11-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_task_options_alter_taskstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={},
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ManyToManyField(blank=True, to='webapp.tasktype', verbose_name='Типы задачи'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип'),
        ),
    ]
